#
#    __                          __
#   / /____ ___ ____  ___  ___ _/ /       This file is provided to you by https://github.com/tegonal/github-commons
#  / __/ -_) _ `/ _ \/ _ \/ _ `/ /        Copyright 2022 Tegonal Genossenschaft <info@tegonal.com>
#  \__/\__/\_, /\___/_//_/\_,_/_/         It is licensed under Creative Commons Zero v1.0 Universal
#         /___/                           Please report bugs and contribute back your improvements
#
#                                         Version: v2.6.0
###################################
name: Cleanup

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.AUTO_PR_DEPLOY_KEY }}
      - name: Cleanup Sources
        run: echo "hello world" > dummy.txt
#      - name: setup ssh
#        run: |
#          if [[ -z $SSH_AUTH_SOCK ]]
#          then
#            echo "Starting agent."
#            LOCAL_SSH_AUTH_SOCK="$(mktemp -t ssh-agent-XXXXXXXXXX).sock"
#            echo "SSH_AUTH_SOCK=${LOCAL_SSH_AUTH_SOCK}" >> $GITHUB_ENV
#            ssh-agent -a "$LOCAL_SSH_AUTH_SOCK" > /dev/null
#          else
#            echo "Agent is already running."
#          fi
#      - name: add deploy key
#        run: |
#          echo "Adding private key."
#          ssh-add - <<< "${{ secrets.AUTO_PR_DEPLOY_KEY }}"
#          cat .git/config
#          perl -0777 -i -pe "s@url = (.*)@url = ssh://\${1}@;" .git/config
#          cat .git/config

      - name: Create Pull Request if necessary
        uses: peter-evans/create-pull-request@v6
        with:
          branch: auto-cleanup
          title: Auto Cleanup
          commit-message: auto cleanup sources
          body: Looks like someone forgot to run ./scripts/cleanup-on-push-to-main.sh before committing. I did it for them :)
          delete-branch: true
          push-to-fork: ${{ vars.AUTO_PR_FORK_NAME != '' && vars.AUTO_PR_FORK_NAME || secrets.AUTO_PR_FORK_NAME }}
